//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EASYTOOLS.MarkDownEditor {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EASYTOOLS.MarkDownEditor.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný @import url(https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.12.0/katex.min.css);.editorContainer[data-v-0d622286]{overflow:hidden;height:100vh}#app{font-family:Avenir,Helvetica,Arial,sans-serif;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}body,html{padding:0;margin:0;box-sizing:border-box;height:100%;overflow:hidden}.splitter-pane{position:fixed!important}.
        /// </summary>
        public static string app {
            get {
                return ResourceManager.GetString("app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (function(e){function t(t){for(var o,a,i=t[0],c=t[1],s=t[2],u=0,m=[];u&lt;i.length;u++)a=i[u],Object.prototype.hasOwnProperty.call(r,a)&amp;&amp;r[a]&amp;&amp;m.push(r[a][0]),r[a]=0;for(o in c)Object.prototype.hasOwnProperty.call(c,o)&amp;&amp;(e[o]=c[o]);l&amp;&amp;l(t);while(m.length)m.shift()();return d.push.apply(d,s||[]),n()}function n(){for(var e,t=0;t&lt;d.length;t++){for(var n=d[t],o=!0,a=1;a&lt;n.length;a++){var c=n[a];0!==r[c]&amp;&amp;(o=!1)}o&amp;&amp;(d.splice(t--,1),e=i(i.s=n[0]))}return e}var o={},r={app:0},d=[];function a(e){return i.p+&quot;js/&quot;+({}[e [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string app1 {
            get {
                return ResourceManager.GetString("app1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-0b65ffb6&quot;],{db4f:function(e,t,n){&quot;use strict&quot;;n.r(t),n.d(t,&quot;setupMode&quot;,(function(){return us}));var i,r=12e4,o=function(){function e(e){var t=this;this._defaults=e,this._worker=null,this._idleCheckInterval=window.setInterval((function(){return t._checkIfIdle()}),3e4),this._lastUsedTime=0,this._configChangeListener=this._defaults.onDidChange((function(){return t._stopWorker()}))}return e.prototype._stopWorker=function(){this._worker&amp;&amp;(this._wo [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_0b65ffb6 {
            get {
                return ResourceManager.GetString("chunk-0b65ffb6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0a3577&quot;],{&quot;0287&quot;:function(e,t,n){&quot;use strict&quot;;n.r(t),n.d(t,&quot;conf&quot;,(function(){return r})),n.d(t,&quot;language&quot;,(function(){return s}));var r={comments:{lineComment:&quot;;;&quot;},brackets:[[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;],[&quot;{&quot;,&quot;}&quot;]],autoClosingPairs:[{open:&quot;[&quot;,close:&quot;]&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&quot;{&quot;,close:&quot;}&quot;}],surroundingPairs:[{open:&quot;[&quot;,close:&quot;]&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&quot;{&quot;,close:&quot;}&quot;}]},s={defaultToken:&quot;&quot;,ignoreCase: [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0a3577 {
            get {
                return ResourceManager.GetString("chunk-2d0a3577", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0a43df&quot;],{&quot;0636&quot;:function(e,t,n){&quot;use strict&quot;;n.r(t),n.d(t,&quot;conf&quot;,(function(){return o})),n.d(t,&quot;language&quot;,(function(){return s}));var o={wordPattern:/(-?\d*\.\d\w*)|([^\`\~\!\#\%\^\&amp;\*\(\)\-\=\+\[\{\]\}\\\|\;\:\&apos;\&quot;\,\.\&lt;\&gt;\/\?\s]+)/g,comments:{lineComment:&quot;//&quot;,blockComment:[&quot;/*&quot;,&quot;*/&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;},{open:&quot;&apos;&quot;,clo [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0a43df {
            get {
                return ResourceManager.GetString("chunk-2d0a43df", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0aa90c&quot;],{&quot;120e&quot;:function(e,n,t){&quot;use strict&quot;;t.r(n),t.d(n,&quot;conf&quot;,(function(){return o})),t.d(n,&quot;language&quot;,(function(){return s}));var o={comments:{lineComment:&quot;#&quot;},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&quot;&quot;&apos;,close:&apos;&quot;&quot;&quot;&apos;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;,notIn:[&quot;string&quot;,&quot;comment&quot;]}],surroundingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot; [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0aa90c {
            get {
                return ResourceManager.GetString("chunk-2d0aa90c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0aab07&quot;],{&quot;11a2&quot;:function(e,n,t){&quot;use strict&quot;;t.r(n),t.d(n,&quot;conf&quot;,(function(){return r})),t.d(n,&quot;language&quot;,(function(){return o}));var r={comments:{lineComment:&quot;#&quot;},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;}],surroundingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;},{open:&quot;&apos;&quot;,cl [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0aab07 {
            get {
                return ResourceManager.GetString("chunk-2d0aab07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0abc00&quot;],{1737:function(e,t,o){&quot;use strict&quot;;o.r(t),o.d(t,&quot;conf&quot;,(function(){return i})),o.d(t,&quot;language&quot;,(function(){return m}));var r=&quot;undefined&quot;===typeof monaco?self.monaco:monaco,n=[&quot;area&quot;,&quot;base&quot;,&quot;br&quot;,&quot;col&quot;,&quot;embed&quot;,&quot;hr&quot;,&quot;img&quot;,&quot;input&quot;,&quot;keygen&quot;,&quot;link&quot;,&quot;menuitem&quot;,&quot;meta&quot;,&quot;param&quot;,&quot;source&quot;,&quot;track&quot;,&quot;wbr&quot;],i={wordPattern:/(-?\d*\.\d\w*)|([^\`\~\!\@\$\^\&amp;\*\(\)\-\=\+\[\{\]\}\\\|\;\:\&apos;\&quot;\,\.\&lt;\&gt;\/\s]+)/g,comments:{blockComment:[&quot;\x3c!--&quot;,&quot;--\x3e&quot;] [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0abc00 {
            get {
                return ResourceManager.GetString("chunk-2d0abc00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0ae937&quot;],{&quot;0b3b&quot;:function(E,T,R){&quot;use strict&quot;;R.r(T),R.d(T,&quot;conf&quot;,(function(){return A})),R.d(T,&quot;language&quot;,(function(){return I}));var A={comments:{lineComment:&quot;--&quot;,blockComment:[&quot;/*&quot;,&quot;*/&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;}],surroundingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos; [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0ae937 {
            get {
                return ResourceManager.GetString("chunk-2d0ae937", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0aeb45&quot;],{&quot;0aca&quot;:function(x,e,i){&quot;use strict&quot;;i.r(e),i.d(e,&quot;conf&quot;,(function(){return d})),i.d(e,&quot;language&quot;,(function(){return f}));var d={comments:{lineComment:&quot;//&quot;,blockComment:[&quot;/*&quot;,&quot;*/&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;],[&quot;&lt;&quot;,&quot;&gt;&quot;]],autoClosingPairs:[{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{open:&quot;{&quot;,close:&quot;}&quot;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{open:&quot;[&quot;,close:&quot;]&quot;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{open:&quot;(&quot;,close:&quot;)&quot;,notIn:[&quot;string&quot;,&quot;com [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0aeb45 {
            get {
                return ResourceManager.GetString("chunk-2d0aeb45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0af08c&quot;],{&quot;0d35&quot;:function(e,t,n){&quot;use strict&quot;;n.r(t),n.d(t,&quot;conf&quot;,(function(){return r})),n.d(t,&quot;language&quot;,(function(){return s}));var r={wordPattern:/(-?\d*\.\d\w*)|([^\`\~\!\@\#%\^\&amp;\*\(\)\=\$\-\+\[\{\]\}\\\|\;\:\&apos;\&quot;\,\.\&lt;\&gt;\/\?\s]+)/g,comments:{blockComment:[&quot;###&quot;,&quot;###&quot;],lineComment:&quot;#&quot;},folding:{markers:{start:new RegExp(&quot;^\\s*#region\\b&quot;),end:new RegExp(&quot;^\\s*#endregion\\b&quot;)}}},s={defaultToken:&quot;&quot;,ignoreCase:!1,tokenPostfix:&quot;.mips&quot;,regE [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0af08c {
            get {
                return ResourceManager.GetString("chunk-2d0af08c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0afa49&quot;],{&quot;0eca&quot;:function(e,n,o){&quot;use strict&quot;;o.r(n),o.d(n,&quot;conf&quot;,(function(){return s})),o.d(n,&quot;language&quot;,(function(){return t}));var s={brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;}],surroundingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;}]},t={defaultToken: [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0afa49 {
            get {
                return ResourceManager.GetString("chunk-2d0afa49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0b2762&quot;],{&quot;23e0&quot;:function(e,t,n){&quot;use strict&quot;;n.r(t),n.d(t,&quot;conf&quot;,(function(){return o})),n.d(t,&quot;language&quot;,(function(){return a}));var o={comments:{lineComment:&quot;//&quot;},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{open:&quot;{&quot;,close:&quot;}&quot;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{open:&quot;[&quot;,close:&quot;]&quot;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{open:&quot;(&quot;,close:&quot;)&quot;,notIn:[ [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0b2762 {
            get {
                return ResourceManager.GetString("chunk-2d0b2762", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0b6187&quot;],{&quot;1c65&quot;:function(_,e,E){&quot;use strict&quot;;E.r(e),E.d(e,&quot;conf&quot;,(function(){return t})),E.d(e,&quot;language&quot;,(function(){return T}));var t={comments:{lineComment:&quot;--&quot;,blockComment:[&quot;/*&quot;,&quot;*/&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;}],surroundingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos; [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0b6187 {
            get {
                return ResourceManager.GetString("chunk-2d0b6187", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0ba136&quot;],{3652:function(e,t,n){&quot;use strict&quot;;n.r(t),n.d(t,&quot;conf&quot;,(function(){return o})),n.d(t,&quot;language&quot;,(function(){return s}));var o={comments:{lineComment:&quot;#&quot;}},s={defaultToken:&quot;keyword&quot;,ignoreCase:!0,tokenPostfix:&quot;.azcli&quot;,str:/[^#\s]/,tokenizer:{root:[{include:&quot;@comment&quot;},[/\s-+@str*\s*/,{cases:{&quot;@eos&quot;:{token:&quot;key.identifier&quot;,next:&quot;@popall&quot;},&quot;@default&quot;:{token:&quot;key.identifier&quot;,next:&quot;@type&quot;}}}],[/^-+@str*\s*/,{cases:{&quot;@eos&quot;:{token:&quot;key.id [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0ba136 {
            get {
                return ResourceManager.GetString("chunk-2d0ba136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0bb267&quot;],{&quot;39f1&quot;:function(e,t,n){&quot;use strict&quot;;n.r(t),n.d(t,&quot;conf&quot;,(function(){return i})),n.d(t,&quot;language&quot;,(function(){return r}));var i={wordPattern:/(#?-?\d*\.\d\w*%?)|([@#!.:]?[\w-?]+%?)|[@#!.]/g,comments:{blockComment:[&quot;/*&quot;,&quot;*/&quot;],lineComment:&quot;//&quot;},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{open:&quot;[&quot;,close:&quot;]&quot;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{open:&quot;(&quot;,close:&quot;)&quot;,notIn:[&quot;string&quot;,&quot; [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0bb267 {
            get {
                return ResourceManager.GetString("chunk-2d0bb267", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0bcec1&quot;],{&quot;2a95&quot;:function(e,_,t){&quot;use strict&quot;;t.r(_),t.d(_,&quot;conf&quot;,(function(){return r})),t.d(_,&quot;language&quot;,(function(){return i}));var r={comments:{lineComment:&quot;--&quot;,blockComment:[&quot;/*&quot;,&quot;*/&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;}],surroundingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos; [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0bcec1 {
            get {
                return ResourceManager.GetString("chunk-2d0bcec1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0bdf38&quot;],{&quot;2dd4&quot;:function(e,n,s){&quot;use strict&quot;;s.r(n),s.d(n,&quot;conf&quot;,(function(){return i})),s.d(n,&quot;language&quot;,(function(){return t}));var i={brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&quot;&lt;&quot;,close:&quot;&gt;&quot;,notIn:[&quot;string&quot;]}],surroundingPairs:[{open:&quot;(&quot;,close:&quot;)&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;`&quot;,close:&quot;`&quot;}],folding:{markers:{start:new RegExp(&quot;^\\s*\x3c!--\\s*#?region\\b [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0bdf38 {
            get {
                return ResourceManager.GetString("chunk-2d0bdf38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0bff92&quot;],{4099:function(e,t,n){&quot;use strict&quot;;n.r(t),n.d(t,&quot;conf&quot;,(function(){return o})),n.d(t,&quot;language&quot;,(function(){return i}));var o={wordPattern:/(#?-?\d*\.\d\w*%?)|([@$#!.:]?[\w-?]+%?)|[@#!.]/g,comments:{blockComment:[&quot;/*&quot;,&quot;*/&quot;],lineComment:&quot;//&quot;},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{open:&quot;[&quot;,close:&quot;]&quot;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{open:&quot;(&quot;,close:&quot;)&quot;,notIn:[&quot;string&quot;,&quot;c [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0bff92 {
            get {
                return ResourceManager.GetString("chunk-2d0bff92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0c0494&quot;],{&quot;40ac&quot;:function(e,t,s){&quot;use strict&quot;;s.r(t),s.d(t,&quot;conf&quot;,(function(){return n})),s.d(t,&quot;language&quot;,(function(){return r}));var n={comments:{lineComment:&quot;#&quot;},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;},{open:&quot;`&quot;,close:&quot;`&quot;}],surroundingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,cl [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0c0494 {
            get {
                return ResourceManager.GetString("chunk-2d0c0494", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0c0a09&quot;],{&quot;431e&quot;:function(e,o,r){&quot;use strict&quot;;r.r(o),r.d(o,&quot;conf&quot;,(function(){return t})),r.d(o,&quot;language&quot;,(function(){return n}));var t={comments:{lineComment:&quot;#&quot;},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;}],surroundingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;}]},n={defaultToken:&quot;&quot;,tokenPostfix [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0c0a09 {
            get {
                return ResourceManager.GetString("chunk-2d0c0a09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0c4313&quot;],{&quot;3a7f&quot;:function(e,n,s){&quot;use strict&quot;;s.r(n),s.d(n,&quot;conf&quot;,(function(){return o})),s.d(n,&quot;language&quot;,(function(){return t}));var o={comments:{lineComment:&quot;#&quot;},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;}],surroundingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;},{open:&quot;&apos;&quot;,cl [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0c4313 {
            get {
                return ResourceManager.GetString("chunk-2d0c4313", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0c46d1&quot;],{&quot;3b7c&quot;:function(e,t,n){&quot;use strict&quot;;n.r(t),n.d(t,&quot;conf&quot;,(function(){return i})),n.d(t,&quot;language&quot;,(function(){return m}));var a=&quot;undefined&quot;===typeof monaco?self.monaco:monaco,r=[&quot;area&quot;,&quot;base&quot;,&quot;br&quot;,&quot;col&quot;,&quot;embed&quot;,&quot;hr&quot;,&quot;img&quot;,&quot;input&quot;,&quot;keygen&quot;,&quot;link&quot;,&quot;menuitem&quot;,&quot;meta&quot;,&quot;param&quot;,&quot;source&quot;,&quot;track&quot;,&quot;wbr&quot;],i={wordPattern:/(-?\d*\.\d\w*)|([^\`\~\!\@\$\^\&amp;\*\(\)\=\+\[\{\]\}\\\|\;\:\&apos;\&quot;\,\.\&lt;\&gt;\/\s]+)/g,comments:{blockComment:[&quot;{{!--&quot;,&quot;--}}&quot;]},br [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0c46d1 {
            get {
                return ResourceManager.GetString("chunk-2d0c46d1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0c512b&quot;],{&quot;3e14&quot;:function(e,t,n){&quot;use strict&quot;;n.r(t),n.d(t,&quot;conf&quot;,(function(){return s})),n.d(t,&quot;language&quot;,(function(){return o}));var s={comments:{blockComment:[&quot;\x3c!--&quot;,&quot;--\x3e&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&quot;&lt;&quot;,close:&quot;&gt;&quot;,notIn:[&quot;string&quot;]}],surroundingPairs:[{open:&quot;(&quot;,close:&quot;)&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;`&quot;,close:&quot;`&quot;}],folding:{markers:{ [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0c512b {
            get {
                return ResourceManager.GetString("chunk-2d0c512b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0cf16e&quot;],{&quot;61da&quot;:function(e,t,n){&quot;use strict&quot;;n.r(t),n.d(t,&quot;conf&quot;,(function(){return i})),n.d(t,&quot;language&quot;,(function(){return o}));var i={comments:{lineComment:&quot;//&quot;,blockComment:[&quot;(*&quot;,&quot;*)&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;],[&quot;&lt;&quot;,&quot;&gt;&quot;]],autoClosingPairs:[{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{open:&quot;{&quot;,close:&quot;}&quot;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{open:&quot;[&quot;,close:&quot;]&quot;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{open:&quot;(&quot;,close:&quot;)&quot;,notIn:[&quot;string&quot;,&quot;com [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0cf16e {
            get {
                return ResourceManager.GetString("chunk-2d0cf16e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0d056d&quot;],{&quot;680e&quot;:function(e,t,n){&quot;use strict&quot;;n.r(t),n.d(t,&quot;conf&quot;,(function(){return o})),n.d(t,&quot;language&quot;,(function(){return a}));var o={wordPattern:/(-?\d*\.\d\w*)|([^\`\~\!\#\%\^\&amp;\*\(\)\-\=\+\[\{\]\}\\\|\;\:\&apos;\&quot;\,\.\&lt;\&gt;\/\?\s]+)/g,comments:{lineComment:&quot;//&quot;,blockComment:[&quot;/*&quot;,&quot;*/&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;},{open:&quot;&apos;&quot;,clo [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0d056d {
            get {
                return ResourceManager.GetString("chunk-2d0d056d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0d0645&quot;],{&quot;687d&quot;:function(e,t,n){&quot;use strict&quot;;n.r(t),n.d(t,&quot;conf&quot;,(function(){return a})),n.d(t,&quot;language&quot;,(function(){return o}));var a={comments:{blockComment:[&quot;\x3c!--&quot;,&quot;--\x3e&quot;]},brackets:[[&quot;&lt;&quot;,&quot;&gt;&quot;]],autoClosingPairs:[{open:&quot;&lt;&quot;,close:&quot;&gt;&quot;},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;}],surroundingPairs:[{open:&quot;&lt;&quot;,close:&quot;&gt;&quot;},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;}]},o={defaultToken:&quot;&quot;,tokenPostfix:&quot;.xml&quot;,ignoreCase:!0,qualifiedName:/(?:[\w\ [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0d0645 {
            get {
                return ResourceManager.GetString("chunk-2d0d0645", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0d61fd&quot;],{&quot;70e3&quot;:function(e,t,n){&quot;use strict&quot;;n.r(t),n.d(t,&quot;conf&quot;,(function(){return o})),n.d(t,&quot;language&quot;,(function(){return s}));var o={comments:{lineComment:&quot;//&quot;,blockComment:[&quot;/*&quot;,&quot;*/&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;],[&quot;&lt;&quot;,&quot;&gt;&quot;]],autoClosingPairs:[{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{open:&quot;{&quot;,close:&quot;}&quot;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{open:&quot;[&quot;,close:&quot;]&quot;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{open:&quot;(&quot;,close:&quot;)&quot;,notIn:[&quot;string&quot;,&quot;com [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0d61fd {
            get {
                return ResourceManager.GetString("chunk-2d0d61fd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0d7e63&quot;],{&quot;797b&quot;:function(e,n,t){&quot;use strict&quot;;t.r(n),t.d(n,&quot;conf&quot;,(function(){return o})),t.d(n,&quot;language&quot;,(function(){return r}));var o={comments:{lineComment:&quot;&apos;&quot;,blockComment:[&quot;/*&quot;,&quot;*/&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;],[&quot;&lt;&quot;,&quot;&gt;&quot;],[&quot;addhandler&quot;,&quot;end addhandler&quot;],[&quot;class&quot;,&quot;end class&quot;],[&quot;enum&quot;,&quot;end enum&quot;],[&quot;event&quot;,&quot;end event&quot;],[&quot;function&quot;,&quot;end function&quot;],[&quot;get&quot;,&quot;end get&quot;],[&quot;if&quot;,&quot;end if&quot;],[&quot;interface&quot;,&quot;end interface&quot;],[&quot;module&quot;,&quot;end m [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0d7e63 {
            get {
                return ResourceManager.GetString("chunk-2d0d7e63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0e1b57&quot;],{&quot;7c1f&quot;:function(e,n,o){&quot;use strict&quot;;o.r(n),o.d(n,&quot;conf&quot;,(function(){return t})),o.d(n,&quot;language&quot;,(function(){return s}));var t={comments:{lineComment:&quot;;&quot;,blockComment:[&quot;#|&quot;,&quot;|#&quot;]},brackets:[[&quot;(&quot;,&quot;)&quot;],[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;}],surroundingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;}]},s={def [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0e1b57 {
            get {
                return ResourceManager.GetString("chunk-2d0e1b57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0e1fbe&quot;],{&quot;7d83&quot;:function(e,n,o){&quot;use strict&quot;;o.r(n),o.d(n,&quot;conf&quot;,(function(){return t})),o.d(n,&quot;language&quot;,(function(){return s}));var t={comments:{lineComment:&quot;//&quot;,blockComment:[&quot;/*&quot;,&quot;*/&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;}],surroundingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos; [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0e1fbe {
            get {
                return ResourceManager.GetString("chunk-2d0e1fbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0e22d6&quot;],{&quot;7e1c&quot;:function(e,n,t){&quot;use strict&quot;;t.r(n),t.d(n,&quot;conf&quot;,(function(){return i})),t.d(n,&quot;language&quot;,(function(){return r}));var i={comments:{lineComment:&quot;//&quot;,blockComment:[&quot;/*&quot;,&quot;*/&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;,notIn:[&quot;string&quot;]}],surroundingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0e22d6 {
            get {
                return ResourceManager.GetString("chunk-2d0e22d6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0e542a&quot;],{9470:function(e,n,o){&quot;use strict&quot;;o.r(n),o.d(n,&quot;conf&quot;,(function(){return t})),o.d(n,&quot;language&quot;,(function(){return s}));var t={comments:{lineComment:&quot;//&quot;,blockComment:[&quot;/*&quot;,&quot;*/&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&quot;`&quot;,close:&quot;`&quot;,notIn:[&quot;string&quot;]},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;,notIn:[&quot;string&quot;]},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;,notIn:[&quot;string&quot;,&quot;comment&quot;]}],surround [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0e542a {
            get {
                return ResourceManager.GetString("chunk-2d0e542a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0e57ec&quot;],{9571:function(e,t,p){&quot;use strict&quot;;p.r(t),p.d(t,&quot;conf&quot;,(function(){return n})),p.d(t,&quot;language&quot;,(function(){return i}));var n={wordPattern:/(-?\d*\.\d\w*)|([^\`\~\!\@\#\%\^\&amp;\*\(\)\-\=\+\[\{\]\}\\\|\;\:\&apos;\&quot;\,\.\&lt;\&gt;\/\?\s]+)/g,comments:{lineComment:&quot;//&quot;,blockComment:[&quot;/*&quot;,&quot;*/&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;,notIn:[&quot;string&quot;]},{open:&quot;[&quot;,close:&quot;]&quot;,notIn:[&quot;string&quot;]},{open:&quot;(&quot;,close:&quot;)&quot;,n [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0e57ec {
            get {
                return ResourceManager.GetString("chunk-2d0e57ec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0e6553&quot;],{&quot;97fe&quot;:function(e,r,o){&quot;use strict&quot;;o.r(r),o.d(r,&quot;conf&quot;,(function(){return i})),o.d(r,&quot;language&quot;,(function(){return t}));var i={comments:{lineComment:&quot;#&quot;},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;},{open:&quot;`&quot;,close:&quot;`&quot;}],surroundingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,cl [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0e6553 {
            get {
                return ResourceManager.GetString("chunk-2d0e6553", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0e6c86&quot;],{&quot;99e5&quot;:function(e,t,o){&quot;use strict&quot;;o.r(t),o.d(t,&quot;conf&quot;,(function(){return n})),o.d(t,&quot;language&quot;,(function(){return r}));var n={wordPattern:/(-?\d*\.\d\w*)|([^\`\~\!\#\%\^\&amp;\*\(\)\-\=\+\[\{\]\}\\\|\;\:\&apos;\&quot;\,\.\&lt;\&gt;\/\?\s]+)/g,comments:{lineComment:&quot;//&quot;,blockComment:[&quot;{&quot;,&quot;}&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;],[&quot;&lt;&quot;,&quot;&gt;&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&quot;&lt;&quot;,close:&quot;&gt;&quot;},{open [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0e6c86 {
            get {
                return ResourceManager.GetString("chunk-2d0e6c86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0ea098&quot;],{&quot;8fa5&quot;:function(E,S,e){&quot;use strict&quot;;e.r(S),e.d(S,&quot;conf&quot;,(function(){return T})),e.d(S,&quot;language&quot;,(function(){return R}));var T={brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;}],surroundingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;}]},R={defaultToken: [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0ea098 {
            get {
                return ResourceManager.GetString("chunk-2d0ea098", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d0f0a11&quot;],{&quot;9cd5&quot;:function(t,e,i){&quot;use strict&quot;;i.r(e),i.d(e,&quot;conf&quot;,(function(){return r})),i.d(e,&quot;language&quot;,(function(){return m}));var r={wordPattern:/(-?\d*\.\d\w*)|([^\`\~\!\@\$\^\&amp;\*\(\)\=\+\[\{\]\}\\\|\;\:\&apos;\&quot;\,\.\&lt;\&gt;\/\s]+)/g,comments:{blockComment:[&quot;{#&quot;,&quot;#}&quot;]},brackets:[[&quot;{#&quot;,&quot;#}&quot;],[&quot;{%&quot;,&quot;%}&quot;],[&quot;{{&quot;,&quot;}}&quot;],[&quot;(&quot;,&quot;)&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;\x3c!--&quot;,&quot;--\x3e&quot;],[&quot;&lt;&quot;,&quot;&gt;&quot;]],autoClosingPairs:[{open:&quot;{# &quot;,close:&quot; #}&quot;},{open:&quot;{% &quot;,close:&quot; %}&quot;},{open:&quot;{{ &quot; [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d0f0a11 {
            get {
                return ResourceManager.GetString("chunk-2d0f0a11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d208ac5&quot;],{a693:function(e,n,s){&quot;use strict&quot;;s.r(n),s.d(n,&quot;conf&quot;,(function(){return t})),s.d(n,&quot;language&quot;,(function(){return o}));var t={wordPattern:/(-?\d*\.\d\w*)|([^\`\~\!\@\#%\^\&amp;\*\(\)\=\+\[\{\]\}\\\|\;\:\&apos;\&quot;\,\.\&lt;\&gt;\/\?\s]+)/g,comments:{lineComment:&quot;#&quot;,blockComment:[&quot;&lt;#&quot;,&quot;#&gt;&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;,notIn:[&quot;string&quot;]}, [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d208ac5 {
            get {
                return ResourceManager.GetString("chunk-2d208ac5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d209408&quot;],{a7ea:function(t,r,e){&quot;use strict&quot;;e.r(r),e.d(r,&quot;conf&quot;,(function(){return s})),e.d(r,&quot;language&quot;,(function(){return n}));var s={brackets:[],autoClosingPairs:[],surroundingPairs:[]},n={keywords:[],typeKeywords:[],tokenPostfix:&quot;.csp&quot;,operators:[],symbols:/[=&gt;&lt;!~?:&amp;|+\-*\/\^%]+/,escapes:/\\(?:[abfnrtv\\&quot;&apos;]|x[0-9A-Fa-f]{1,4}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})/,tokenizer:{root:[[/child-src/,&quot;string.quote&quot;],[/connect-src/,&quot;string.quote&quot;],[/ [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d209408 {
            get {
                return ResourceManager.GetString("chunk-2d209408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d20f745&quot;],{b463:function(E,T,S){&quot;use strict&quot;;S.r(T),S.d(T,&quot;conf&quot;,(function(){return R})),S.d(T,&quot;language&quot;,(function(){return A}));var R={comments:{lineComment:&quot;--&quot;,blockComment:[&quot;/*&quot;,&quot;*/&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;}],surroundingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos; [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d20f745 {
            get {
                return ResourceManager.GetString("chunk-2d20f745", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d20ff23&quot;],{b692:function(e,t,n){&quot;use strict&quot;;n.r(t),n.d(t,&quot;conf&quot;,(function(){return r})),n.d(t,&quot;language&quot;,(function(){return d}));var i=&quot;undefined&quot;===typeof monaco?self.monaco:monaco,o=[&quot;area&quot;,&quot;base&quot;,&quot;br&quot;,&quot;col&quot;,&quot;embed&quot;,&quot;hr&quot;,&quot;img&quot;,&quot;input&quot;,&quot;keygen&quot;,&quot;link&quot;,&quot;menuitem&quot;,&quot;meta&quot;,&quot;param&quot;,&quot;source&quot;,&quot;track&quot;,&quot;wbr&quot;],r={wordPattern:/(-?\d*\.\d\w*)|([^\`\~\!\@\$\^\&amp;\*\(\)\=\+\[\{\]\}\\\|\;\:\&apos;\&quot;\,\.\&lt;\&gt;\/\s]+)/g,comments:{blockComment:[&quot;\x3c!--&quot;,&quot;--\x3e&quot;]}, [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d20ff23 {
            get {
                return ResourceManager.GetString("chunk-2d20ff23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d2138c7&quot;],{acc2:function(e,n,o){&quot;use strict&quot;;o.r(n),o.d(n,&quot;conf&quot;,(function(){return t})),o.d(n,&quot;language&quot;,(function(){return r}));var t={comments:{lineComment:&quot;//&quot;,blockComment:[&quot;(*&quot;,&quot;*)&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;],[&quot;var&quot;,&quot;end_var&quot;],[&quot;var_input&quot;,&quot;end_var&quot;],[&quot;var_output&quot;,&quot;end_var&quot;],[&quot;var_in_out&quot;,&quot;end_var&quot;],[&quot;var_temp&quot;,&quot;end_var&quot;],[&quot;var_global&quot;,&quot;end_var&quot;],[&quot;var_access&quot;,&quot;end_var&quot;],[&quot;var_external&quot;,&quot;end_var&quot;],[&quot;type&quot;,&quot;end_type&quot;],[&quot;s [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d2138c7 {
            get {
                return ResourceManager.GetString("chunk-2d2138c7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d217e5b&quot;],{c94c:function(e,n,o){&quot;use strict&quot;;o.r(n),o.d(n,&quot;conf&quot;,(function(){return t})),o.d(n,&quot;language&quot;,(function(){return s}));var t={comments:{lineComment:&quot;--&quot;,blockComment:[&quot;--[[&quot;,&quot;]]&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;}],surroundingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos; [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d217e5b {
            get {
                return ResourceManager.GetString("chunk-2d217e5b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d21b84a&quot;],{bfb2:function(e,t,n){&quot;use strict&quot;;n.r(t),n.d(t,&quot;conf&quot;,(function(){return r})),n.d(t,&quot;language&quot;,(function(){return i}));var r={wordPattern:/(#?-?\d*\.\d\w*%?)|((::|[@#.!:])?[\w-?]+%?)|::|[@#.!:]/g,comments:{blockComment:[&quot;/*&quot;,&quot;*/&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{open:&quot;[&quot;,close:&quot;]&quot;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{open:&quot;(&quot;,close:&quot;)&quot;,notIn:[&quot;string&quot;,&quot;comment&quot;]} [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d21b84a {
            get {
                return ResourceManager.GetString("chunk-2d21b84a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d21dcd2&quot;],{d39f:function(e,t,o){&quot;use strict&quot;;o.r(t),o.d(t,&quot;conf&quot;,(function(){return n})),o.d(t,&quot;language&quot;,(function(){return i}));
        ////*!---------------------------------------------------------------------------------------------
        /// *  Copyright (C) David Owens II, owensd.io. All rights reserved.
        /// *--------------------------------------------------------------------------------------------*/
        ///var n={comments:{lineComment:&quot;//&quot;,blockComment:[&quot;/*&quot;,&quot; [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d21dcd2 {
            get {
                return ResourceManager.GetString("chunk-2d21dcd2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d21f327&quot;],{d995:function(e,n,r){&quot;use strict&quot;;r.r(n),r.d(n,&quot;conf&quot;,(function(){return t})),r.d(n,&quot;language&quot;,(function(){return s}));var t={wordPattern:/(-?\d*\.\d\w*)|([^\`\~\!\@\#%\^\&amp;\*\(\)\=\$\-\+\[\{\]\}\\\|\;\:\&apos;\&quot;\,\.\&lt;\&gt;\/\?\s]+)/g,comments:{blockComment:[&quot;###&quot;,&quot;###&quot;],lineComment:&quot;#&quot;},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;},{open:&quot;&apos;&quot;,c [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d21f327 {
            get {
                return ResourceManager.GetString("chunk-2d21f327", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d2214b3&quot;],{ca76:function(e,n,o){&quot;use strict&quot;;o.r(n),o.d(n,&quot;conf&quot;,(function(){return t})),o.d(n,&quot;language&quot;,(function(){return r}));var t={comments:{lineComment:&quot;&apos;&quot;},brackets:[[&quot;(&quot;,&quot;)&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;If&quot;,&quot;EndIf&quot;],[&quot;While&quot;,&quot;EndWhile&quot;],[&quot;For&quot;,&quot;EndFor&quot;],[&quot;Sub&quot;,&quot;EndSub&quot;]],autoClosingPairs:[{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{open:&quot;(&quot;,close:&quot;)&quot;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{open:&quot;[&quot;,close:&quot;]&quot;,notIn:[&quot;string&quot;,&quot;comment&quot;]}]},r={defaultToken: [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d2214b3 {
            get {
                return ResourceManager.GetString("chunk-2d2214b3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d221799&quot;],{cb04:function(e,o,n){&quot;use strict&quot;;n.r(o),n.d(o,&quot;conf&quot;,(function(){return t})),n.d(o,&quot;language&quot;,(function(){return s}));var t={comments:{lineComment:&quot;//&quot;,blockComment:[&quot;(*&quot;,&quot;*)&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;],[&quot;&lt;&quot;,&quot;&gt;&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&quot;&lt;&quot;,close:&quot;&gt;&quot;},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;}],surroundingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;} [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d221799 {
            get {
                return ResourceManager.GetString("chunk-2d221799", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d221814&quot;],{cb43:function(e,n,t){&quot;use strict&quot;;t.r(n),t.d(n,&quot;conf&quot;,(function(){return i})),t.d(n,&quot;language&quot;,(function(){return o}));var i={wordPattern:/(-?\d*\.\d\w*)|([^\`\~\!\#\%\^\&amp;\*\(\)\-\=\+\[\{\]\}\\\|\;\:\&apos;\&quot;\,\.\&lt;\&gt;\/\?\s]+)/g,comments:{lineComment:&quot;//&quot;,blockComment:[&quot;/*&quot;,&quot;*/&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;},{open:&quot;&apos;&quot;,close [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d221814 {
            get {
                return ResourceManager.GetString("chunk-2d221814", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d221a34&quot;],{cacc:function(e,n,t){&quot;use strict&quot;;t.r(n),t.d(n,&quot;conf&quot;,(function(){return s})),t.d(n,&quot;language&quot;,(function(){return o}));var s={comments:{lineComment:&quot;//&quot;,blockComment:[&quot;(*&quot;,&quot;*)&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;}],surroundingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;},{open:&quot;&apos;&quot; [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d221a34 {
            get {
                return ResourceManager.GetString("chunk-2d221a34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d22502a&quot;],{e328:function(e,t,n){&quot;use strict&quot;;n.r(t),n.d(t,&quot;setupTypeScript&quot;,(function(){return E})),n.d(t,&quot;setupJavaScript&quot;,(function(){return M})),n.d(t,&quot;getJavaScriptWorker&quot;,(function(){return K})),n.d(t,&quot;getTypeScriptWorker&quot;,(function(){return L}));var r,o=function(e,t,n,r){function o(e){return e instanceof n?e:new n((function(t){t(e)}))}return new(n||(n=Promise))((function(n,i){function a(e){try{u(r.next(e))}catch(t){i(t)}}function s(e){ [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d22502a {
            get {
                return ResourceManager.GetString("chunk-2d22502a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d226775&quot;],{e97b:function(e,n,t){&quot;use strict&quot;;t.r(n),t.d(n,&quot;conf&quot;,(function(){return o})),t.d(n,&quot;language&quot;,(function(){return s}));var o={comments:{lineComment:&quot;*&quot;},brackets:[[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]]},i=[&quot;abstract&quot;,&quot;add&quot;,&quot;add-corresponding&quot;,&quot;adjacent&quot;,&quot;alias&quot;,&quot;aliases&quot;,&quot;all&quot;,&quot;append&quot;,&quot;appending&quot;,&quot;ascending&quot;,&quot;as&quot;,&quot;assert&quot;,&quot;assign&quot;,&quot;assigned&quot;,&quot;assigning&quot;,&quot;association&quot;,&quot;authority-check&quot;,&quot;back&quot;,&quot;begin&quot;,&quot;binary&quot;,&quot;block&quot;,&quot;bound&quot;,&quot;break-point&quot;,&quot;by&quot;,&quot;byt [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d226775 {
            get {
                return ResourceManager.GetString("chunk-2d226775", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d229411&quot;],{dd50:function(e,n,t){&quot;use strict&quot;;t.r(n),t.d(n,&quot;conf&quot;,(function(){return o})),t.d(n,&quot;language&quot;,(function(){return s}));var o={comments:{lineComment:&quot;//&quot;,blockComment:[&quot;(*&quot;,&quot;*)&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;],[&quot;&lt;&quot;,&quot;&gt;&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&quot;&lt;&quot;,close:&quot;&gt;&quot;},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;}],surroundingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;} [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d229411 {
            get {
                return ResourceManager.GetString("chunk-2d229411", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d2295e9&quot;],{dcc7:function(e,n,t){&quot;use strict&quot;;t.r(n),t.d(n,&quot;conf&quot;,(function(){return r})),t.d(n,&quot;language&quot;,(function(){return o}));var r={comments:{lineComment:&quot;#&quot;,blockComment:[&quot;=begin&quot;,&quot;=end&quot;]},brackets:[[&quot;(&quot;,&quot;)&quot;],[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;}],surroundingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{ope [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d2295e9 {
            get {
                return ResourceManager.GetString("chunk-2d2295e9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d22c171&quot;],{f26e:function(E,T,A){&quot;use strict&quot;;A.r(T),A.d(T,&quot;conf&quot;,(function(){return N})),A.d(T,&quot;language&quot;,(function(){return R}));var N={comments:{lineComment:&quot;//&quot;,blockComment:[&quot;/*&quot;,&quot;*/&quot;]},brackets:[[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;],[&quot;{&quot;,&quot;}&quot;]],autoClosingPairs:[{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{open:&quot;[&quot;,close:&quot;]&quot;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{open:&quot;(&quot;,close:&quot;)&quot;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{ope [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d22c171 {
            get {
                return ResourceManager.GetString("chunk-2d22c171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d22c2b8&quot;],{f1a8:function(e,n,t){&quot;use strict&quot;;t.r(n),t.d(n,&quot;conf&quot;,(function(){return r})),t.d(n,&quot;language&quot;,(function(){return o}));var s=&quot;undefined&quot;===typeof monaco?self.monaco:monaco,r={comments:{lineComment:&quot;#&quot;,blockComment:[&quot;&apos;&apos;&apos;&quot;,&quot;&apos;&apos;&apos;&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;,notIn:[&quot;string&quot;]},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;,notIn:[&quot;string&quot;,&quot;comment&quot; [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d22c2b8 {
            get {
                return ResourceManager.GetString("chunk-2d22c2b8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d22ca58&quot;],{f3b7:function(e,n,t){&quot;use strict&quot;;t.r(n),t.d(n,&quot;conf&quot;,(function(){return r})),t.d(n,&quot;language&quot;,(function(){return i}));var o=&quot;undefined&quot;===typeof monaco?self.monaco:monaco,r={wordPattern:/(-?\d*\.\d\w*)|([^\`\~\!\@\#\%\^\&amp;\*\(\)\-\=\+\[\{\]\}\\\|\;\:\&apos;\&quot;\,\.\&lt;\&gt;\/\?\s]+)/g,comments:{lineComment:&quot;//&quot;,blockComment:[&quot;/*&quot;,&quot;*/&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],onEnterRules:[{beforeText:/^\s*\/\*\*(?!\/)([^\*]|\*(?!\/))*$/,aft [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d22ca58 {
            get {
                return ResourceManager.GetString("chunk-2d22ca58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d2311f7&quot;],{eecd:function(e,s,o){&quot;use strict&quot;;o.r(s),o.d(s,&quot;conf&quot;,(function(){return n})),o.d(s,&quot;language&quot;,(function(){return t}));var n={comments:{lineComment:&quot;REM&quot;},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;}],surroundingPairs:[{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;}],folding:{markers:{start:new RegExp(&quot;^\\s*(::\\s*|REM\ [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d2311f7 {
            get {
                return ResourceManager.GetString("chunk-2d2311f7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d237ee7&quot;],{fce9:function(e,t,n){&quot;use strict&quot;;n.r(t),n.d(t,&quot;conf&quot;,(function(){return o})),n.d(t,&quot;language&quot;,(function(){return s}));var o={wordPattern:/(-?\d*\.\d\w*)|([^\`\~\!\#\$\%\^\&amp;\*\(\)\-\=\+\[\{\]\}\\\|\;\:\&apos;\&quot;\,\.\&lt;\&gt;\/\?\s]+)/g,comments:{lineComment:&quot;//&quot;,blockComment:[&quot;/*&quot;,&quot;*/&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;,notIn:[&quot;string [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d237ee7 {
            get {
                return ResourceManager.GetString("chunk-2d237ee7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-2d238465&quot;],{ff4c:function(e,t,o){&quot;use strict&quot;;o.r(t),o.d(t,&quot;conf&quot;,(function(){return n})),o.d(t,&quot;language&quot;,(function(){return s}));var n={comments:{lineComment:&quot;//&quot;,blockComment:[&quot;/*&quot;,&quot;*/&quot;]},brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;,notIn:[&quot;string&quot;,&quot;comment&quot;]},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;,notIn:[&quot;string&quot;]}],surroundingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot; [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_2d238465 {
            get {
                return ResourceManager.GetString("chunk-2d238465", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-30597b4a&quot;],{&quot;36c6&quot;:function(e,t,n){&quot;use strict&quot;;(function(e){n.d(t,&quot;a&quot;,(function(){return g}));var i,r,a=function(){var e=function(t,n){return e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&amp;&amp;function(e,t){e.__proto__=t}||function(e,t){for(var n in t)t.hasOwnProperty(n)&amp;&amp;(e[n]=t[n])},e(t,n)};return function(t,n){function i(){this.constructor=t}e(t,n),t.prototype=null===n?Object.create(n):(i.prototype=n.prototype,new i)}}();if(&quot;object&quot; [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_30597b4a {
            get {
                return ResourceManager.GetString("chunk-30597b4a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-7498b54e&quot;],{&quot;5b540&quot;:function(e,t,a){&quot;use strict&quot;;a.r(t),a.d(t,&quot;conf&quot;,(function(){return n})),a.d(t,&quot;language&quot;,(function(){return i}));var n={comments:{lineComment:&quot;//&quot;,blockComment:[&quot;/*&quot;,&quot;*/&quot;]},brackets:[[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;],[&quot;{&quot;,&quot;}&quot;]],autoClosingPairs:[{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;,notIn:[&quot;string&quot;,&quot;comment&quot;,&quot;identifier&quot;]},{open:&quot;[&quot;,close:&quot;]&quot;,notIn:[&quot;string&quot;,&quot;comment&quot;,&quot;identifier&quot;]},{open:&quot;(&quot;,close:&quot;)&quot;,notIn:[&quot;string&quot;,&quot;comment&quot;,&quot;identifier&quot;]},{open:&quot;{&quot;, [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_7498b54e {
            get {
                return ResourceManager.GetString("chunk-7498b54e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-7532b3ea&quot;,&quot;chunk-2d22ca58&quot;],{ed79:function(e,n,t){&quot;use strict&quot;;t.r(n),t.d(n,&quot;conf&quot;,(function(){return i})),t.d(n,&quot;language&quot;,(function(){return r}));var o=t(&quot;f3b7&quot;),i=(&quot;undefined&quot;===typeof monaco?self.monaco:monaco,o[&quot;conf&quot;]),r={defaultToken:&quot;invalid&quot;,tokenPostfix:&quot;.js&quot;,keywords:[&quot;break&quot;,&quot;case&quot;,&quot;catch&quot;,&quot;class&quot;,&quot;continue&quot;,&quot;const&quot;,&quot;constructor&quot;,&quot;debugger&quot;,&quot;default&quot;,&quot;delete&quot;,&quot;do&quot;,&quot;else&quot;,&quot;export&quot;,&quot;extends&quot;,&quot;false&quot;,&quot;finally&quot;,&quot;for&quot;,&quot;from&quot;,&quot;function&quot; [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_7532b3ea {
            get {
                return ResourceManager.GetString("chunk-7532b3ea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-770c7886&quot;],{c53fa:function(e,t,n){&quot;use strict&quot;;n.r(t),n.d(t,&quot;conf&quot;,(function(){return o})),n.d(t,&quot;language&quot;,(function(){return s}));var o={brackets:[[&quot;{&quot;,&quot;}&quot;],[&quot;[&quot;,&quot;]&quot;],[&quot;(&quot;,&quot;)&quot;]],autoClosingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;}],surroundingPairs:[{open:&quot;{&quot;,close:&quot;}&quot;},{open:&quot;[&quot;,close:&quot;]&quot;},{open:&quot;(&quot;,close:&quot;)&quot;},{open:&apos;&quot;&apos;,close:&apos;&quot;&apos;},{open:&quot;&apos;&quot;,close:&quot;&apos;&quot;}]},s={tokenPostfix:&quot; [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_770c7886 {
            get {
                return ResourceManager.GetString("chunk-770c7886", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-e13e4362&quot;],{&quot;47b9&quot;:function(e,t,n){&quot;use strict&quot;;n.r(t),n.d(t,&quot;setupMode&quot;,(function(){return mn}));var r,i=12e4,o=function(){function e(e){var t=this;this._defaults=e,this._worker=null,this._idleCheckInterval=setInterval((function(){return t._checkIfIdle()}),3e4),this._lastUsedTime=0,this._configChangeListener=this._defaults.onDidChange((function(){return t._stopWorker()}))}return e.prototype._stopWorker=function(){this._worker&amp;&amp;(this._worker. [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_e13e4362 {
            get {
                return ResourceManager.GetString("chunk-e13e4362", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný .monaco-editor .accessibilityHelpWidget{padding:10px;vertical-align:middle;overflow:scroll}.monaco-aria-container{position:absolute;left:-999em}.monaco-editor .bracket-match{box-sizing:border-box}.monaco-menu .monaco-action-bar.vertical .action-label.hover{background-color:#eee}.monaco-editor .monaco-editor-overlaymessage{padding-bottom:8px}@-webkit-keyframes fadeIn{0%{opacity:0}to{opacity:1}}@keyframes fadeIn{0%{opacity:0}to{opacity:1}}.monaco-editor .monaco-editor-overlaymessage.fadeIn{-webkit-animation:f [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_vendors {
            get {
                return ResourceManager.GetString("chunk-vendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-vendors&quot;],{&quot;0068&quot;:function(e,t,n){&quot;use strict&quot;;function i(e){return Object.prototype.toString.call(e)}function r(e){return&quot;[object String]&quot;===i(e)}var o=Object.prototype.hasOwnProperty;function a(e,t){return o.call(e,t)}function s(e){var t=Array.prototype.slice.call(arguments,1);return t.forEach((function(t){if(t){if(&quot;object&quot;!==typeof t)throw new TypeError(t+&quot;must be object&quot;);Object.keys(t).forEach((function(n){e[n]=t[n]}))}})),e}function l(e [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string chunk_vendors1 {
            get {
                return ResourceManager.GetString("chunk-vendors1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        public static byte[] codicon {
            get {
                object obj = ResourceManager.GetObject("codicon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (function(e){var t={};function n(i){if(t[i])return t[i].exports;var r=t[i]={i:i,l:!1,exports:{}};return e[i].call(r.exports,r,r.exports,n),r.l=!0,r.exports}n.m=e,n.c=t,n.d=function(e,t,i){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:i})},n.r=function(e){&quot;undefined&quot;!==typeof Symbol&amp;&amp;Symbol.toStringTag&amp;&amp;Object.defineProperty(e,Symbol.toStringTag,{value:&quot;Module&quot;}),Object.defineProperty(e,&quot;__esModule&quot;,{value:!0})},n.t=function(e,t){if(1&amp;t&amp;&amp;(e=n(e)),8&amp;t)return e;if(4&amp;t&amp;&amp;&quot;object&quot;===typeof e&amp;&amp;e&amp;&amp;e.__esMo [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string css_worker {
            get {
                return ResourceManager.GetString("css.worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        public static byte[] editor {
            get {
                object obj = ResourceManager.GetObject("editor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (function(e){var t={};function n(r){if(t[r])return t[r].exports;var i=t[r]={i:r,l:!1,exports:{}};return e[r].call(i.exports,i,i.exports,n),i.l=!0,i.exports}n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){&quot;undefined&quot;!==typeof Symbol&amp;&amp;Symbol.toStringTag&amp;&amp;Object.defineProperty(e,Symbol.toStringTag,{value:&quot;Module&quot;}),Object.defineProperty(e,&quot;__esModule&quot;,{value:!0})},n.t=function(e,t){if(1&amp;t&amp;&amp;(e=n(e)),8&amp;t)return e;if(4&amp;t&amp;&amp;&quot;object&quot;===typeof e&amp;&amp;e&amp;&amp;e.__esMo [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string editor_worker {
            get {
                return ResourceManager.GetString("editor.worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        public static byte[] en_US {
            get {
                object obj = ResourceManager.GetObject("en_US", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Icon podobný (Ikona).
        /// </summary>
        public static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (function(e){var t={};function n(i){if(t[i])return t[i].exports;var r=t[i]={i:i,l:!1,exports:{}};return e[i].call(r.exports,r,r.exports,n),r.l=!0,r.exports}n.m=e,n.c=t,n.d=function(e,t,i){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:i})},n.r=function(e){&quot;undefined&quot;!==typeof Symbol&amp;&amp;Symbol.toStringTag&amp;&amp;Object.defineProperty(e,Symbol.toStringTag,{value:&quot;Module&quot;}),Object.defineProperty(e,&quot;__esModule&quot;,{value:!0})},n.t=function(e,t){if(1&amp;t&amp;&amp;(e=n(e)),8&amp;t)return e;if(4&amp;t&amp;&amp;&quot;object&quot;===typeof e&amp;&amp;e&amp;&amp;e.__esMo [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string html_worker {
            get {
                return ResourceManager.GetString("html.worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný &lt;!DOCTYPE html&gt;&lt;html lang=en&gt;&lt;head&gt;&lt;meta charset=utf-8&gt;&lt;meta http-equiv=X-UA-Compatible content=&quot;IE=edge&quot;&gt;&lt;meta name=viewport content=&quot;width=device-width,initial-scale=1&quot;&gt;&lt;link rel=icon href=favicon.ico&gt;&lt;title&gt;vue-monaco-editor&lt;/title&gt;&lt;link href=js/chunk-0b65ffb6.js rel=prefetch&gt;&lt;link href=js/chunk-2d0a3577.js rel=prefetch&gt;&lt;link href=js/chunk-2d0a43df.js rel=prefetch&gt;&lt;link href=js/chunk-2d0aa90c.js rel=prefetch&gt;&lt;link href=js/chunk-2d0aab07.js rel=prefetch&gt;&lt;link href=js/chunk-2d0abc00.js rel=prefetch&gt;&lt;link h [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (function(e){var t={};function n(r){if(t[r])return t[r].exports;var i=t[r]={i:r,l:!1,exports:{}};return e[r].call(i.exports,i,i.exports,n),i.l=!0,i.exports}n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){&quot;undefined&quot;!==typeof Symbol&amp;&amp;Symbol.toStringTag&amp;&amp;Object.defineProperty(e,Symbol.toStringTag,{value:&quot;Module&quot;}),Object.defineProperty(e,&quot;__esModule&quot;,{value:!0})},n.t=function(e,t){if(1&amp;t&amp;&amp;(e=n(e)),8&amp;t)return e;if(4&amp;t&amp;&amp;&quot;object&quot;===typeof e&amp;&amp;e&amp;&amp;e.__esMo [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string json_worker {
            get {
                return ResourceManager.GetString("json.worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný (function(e){var n={};function t(r){if(n[r])return n[r].exports;var a=n[r]={i:r,l:!1,exports:{}};return e[r].call(a.exports,a,a.exports,t),a.l=!0,a.exports}t.m=e,t.c=n,t.d=function(e,n,r){t.o(e,n)||Object.defineProperty(e,n,{enumerable:!0,get:r})},t.r=function(e){&quot;undefined&quot;!==typeof Symbol&amp;&amp;Symbol.toStringTag&amp;&amp;Object.defineProperty(e,Symbol.toStringTag,{value:&quot;Module&quot;}),Object.defineProperty(e,&quot;__esModule&quot;,{value:!0})},t.t=function(e,n){if(1&amp;n&amp;&amp;(e=t(e)),8&amp;n)return e;if(4&amp;n&amp;&amp;&quot;object&quot;===typeof e&amp;&amp;e&amp;&amp;e.__esMo [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string ts_worker {
            get {
                return ResourceManager.GetString("ts.worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        public static byte[] zh_CN {
            get {
                object obj = ResourceManager.GetObject("zh_CN", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
