//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EASYTools.HTMLFullEditor.Localization {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DefaultResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultResources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EASYTools.HTMLFullEditor.Localization.DefaultResources", typeof(DefaultResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Delete.
        /// </summary>
        public static string ContextMenu_Delete {
            get {
                return ResourceManager.GetString("ContextMenu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Browse....
        /// </summary>
        public static string Form_Browse {
            get {
                return ResourceManager.GetString("Form_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cancel.
        /// </summary>
        public static string Form_Cancel {
            get {
                return ResourceManager.GetString("Form_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný OK.
        /// </summary>
        public static string Form_OK {
            get {
                return ResourceManager.GetString("Form_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Image.
        /// </summary>
        public static string ImageForm_DefaultAltText {
            get {
                return ResourceManager.GetString("ImageForm_DefaultAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Make image physically smaller.
        /// </summary>
        public static string ImageForm_DoPhysicalResize {
            get {
                return ResourceManager.GetString("ImageForm_DoPhysicalResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Image file cannot be loaded.
        /// </summary>
        public static string ImageForm_ErrorImage {
            get {
                return ResourceManager.GetString("ImageForm_ErrorImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Image files.
        /// </summary>
        public static string ImageForm_Filter {
            get {
                return ResourceManager.GetString("ImageForm_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Height.
        /// </summary>
        public static string ImageForm_Height {
            get {
                return ResourceManager.GetString("ImageForm_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Image.
        /// </summary>
        public static string ImageForm_Path {
            get {
                return ResourceManager.GetString("ImageForm_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Preview.
        /// </summary>
        public static string ImageForm_Preview {
            get {
                return ResourceManager.GetString("ImageForm_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Show real size.
        /// </summary>
        public static string ImageForm_ShowRealSize {
            get {
                return ResourceManager.GetString("ImageForm_ShowRealSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Size.
        /// </summary>
        public static string ImageForm_Size {
            get {
                return ResourceManager.GetString("ImageForm_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Title.
        /// </summary>
        public static string ImageForm_Title {
            get {
                return ResourceManager.GetString("ImageForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Width.
        /// </summary>
        public static string ImageForm_Width {
            get {
                return ResourceManager.GetString("ImageForm_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Text.
        /// </summary>
        public static string LinkForm_Text {
            get {
                return ResourceManager.GetString("LinkForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný URL.
        /// </summary>
        public static string LinkForm_Url {
            get {
                return ResourceManager.GetString("LinkForm_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Text align center.
        /// </summary>
        public static string Text_AlignCenter {
            get {
                return ResourceManager.GetString("Text_AlignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Text align left.
        /// </summary>
        public static string Text_AlignLeft {
            get {
                return ResourceManager.GetString("Text_AlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Text align right.
        /// </summary>
        public static string Text_AlignRight {
            get {
                return ResourceManager.GetString("Text_AlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Background color.
        /// </summary>
        public static string Text_BackgroundColor {
            get {
                return ResourceManager.GetString("Text_BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Bold.
        /// </summary>
        public static string Text_Bold {
            get {
                return ResourceManager.GetString("Text_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unordered list.
        /// </summary>
        public static string Text_BulletList {
            get {
                return ResourceManager.GetString("Text_BulletList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Line highlight color.
        /// </summary>
        public static string Text_HighlightColor {
            get {
                return ResourceManager.GetString("Text_HighlightColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Show HTML code.
        /// </summary>
        public static string Text_HtmlCode {
            get {
                return ResourceManager.GetString("Text_HtmlCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Insert image.
        /// </summary>
        public static string Text_Image {
            get {
                return ResourceManager.GetString("Text_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Bigger indent.
        /// </summary>
        public static string Text_Indent {
            get {
                return ResourceManager.GetString("Text_Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Italic.
        /// </summary>
        public static string Text_Italic {
            get {
                return ResourceManager.GetString("Text_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Insert link.
        /// </summary>
        public static string Text_Link {
            get {
                return ResourceManager.GetString("Text_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Ordered list.
        /// </summary>
        public static string Text_NumberedList {
            get {
                return ResourceManager.GetString("Text_NumberedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Smaller indent.
        /// </summary>
        public static string Text_Outdent {
            get {
                return ResourceManager.GetString("Text_Outdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Text color.
        /// </summary>
        public static string Text_TextColor {
            get {
                return ResourceManager.GetString("Text_TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Underline.
        /// </summary>
        public static string Text_Underline {
            get {
                return ResourceManager.GetString("Text_Underline", resourceCulture);
            }
        }
    }
}
